### ISSUE TITLE
No Nodes listed on Status Page

### ISSUE THREAD

**Issue by fibidifips** [ClusterLabs/hawk#58]
- browser debug shows a syntax error for nodes.json:1
- Graph isn't working too

**Comment by krig** [comment]
Which version are you running?

**Comment by fibidifips** [comment]
download master yesterday

SLES11.3
Pacemaker1.1.13-42a56cb

**Comment by krig** [comment]
Which browser and browser version are you testing with? It sounds like something is going very wrong somewhere, but I'm not sure what or where.

**Comment by fibidifips** [comment]
Firefox 33, same issue with other browsers (chrome, IE).
had this issue since move to puma. with lighttpd it worked as expected.

**Comment by krig** [comment]
Aah yes, that sounds like it could be where things are breaking. The question then is why puma is misbehaving for you...

Could you check your logs for anything related to puma? `/var/log/messages`, any other logs you might find under `/var/log`, any logs from `/srv/www/hawk/log/`? Thanks!

**Comment by fibidifips** [comment]
hi,

no messages in default linux logs.
when starting with "test" environment, this is the only error i see:

Rack app error: #<NoMethodError: undefined method `uname' for #<Node:0x007fa58563f970>
---
"development" for debugging isn't working at all, here no login on webui is possible:

HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>

**Comment by fibidifips** [comment]
more extended log info, after pressing refresh button on nodes section:

Completed 200 OK in 60019ms
Started GET "/cib/live/nodes.json?sort=name&order=asc&limit=50&offset=0" for 10.1.0.212 at 2015-10-08 11:45:23 +0200
Processing by NodesController#index as JSON
  Parameters: {"sort"=>"name", "order"=>"asc", "limit"=>"50", "offset"=>"0", "cib_id"=>"live", "node"=>{}}
Cib.initialize live, hacluster, false
Executing `"cibadmin -Ql"` through `run_as`
Executing `/usr/sbin/crm_simulate -LU` through `safe_x`
Completed 500 Internal Server Error in 696ms
2015-10-08 11:45:23 +0200: Rack app error: #\<NoMethodError: undefined method `uname' for #\<Node:0x00000005514f78\>\>

**Comment by krig** [comment]
Ah, excellent, the Node uname issue probably is a bug I can fix, if the node element doesn't have `uname` set (which seems to be the case for you).

The puma HTTP parse error on the other hand, is difficult to solve without being able to reproduce myself. But I will keep this issue open.

**Comment by krig** [comment]
Please test again with the above fix.

**Comment by fibidifips** [comment]
another message:

2015-10-08 12:51:55 +0200: Rack app error: #\<TypeError: no implicit conversion of Symbol into Integer\>
/srv/www/hawk/app/models/node.rb:120:in `[]='
/srv/www/hawk/app/models/node.rb:120:in `block (2 levels) in instantiate'
/srv/www/hawk/app/models/node.rb:116:in `each'
/srv/www/hawk/app/models/node.rb:116:in `block in instantiate'
/srv/www/hawk/app/models/node.rb:110:in `each'
/srv/www/hawk/app/models/node.rb:110:in `instantiate'
/srv/www/hawk/app/models/cib.rb:239:in `block in nodes_ordered'

**Comment by fibidifips** [comment]
hi,

looks like this is due to resource utilization stanza "if record.utilization.any?" in node.rb. 
i comment record.utilization.any, afterwards nodes show up as expected.

i have placement-strategy activated in my cluster

**Comment by krig** [comment]
thanks!

**Comment by krig** [comment]
This should be fixed now.

**Comment by fibidifips** [comment]
hi,

yes, nodes show up correctly now. thank you!

- but: pressing "details" button didn't show anything. in previous version this shows up remaing cpu/mem for host. may this will be another issue?

**Comment by krig** [comment]
Yeah, that sounds like another issue :/
I will look into it.

**Comment by fibidifips** [comment]
found this:

2015-10-08 14:18:40 +0200: Rack app error: #\<ActionView::Template::Error: nil can't be coerced into Fixnum\>
/srv/www/hawk/app/views/nodes/show.html.haml:27:in `-'
/srv/www/hawk/app/views/nodes/show.html.haml:27:in `block in _app_views_nodes_show_html_haml___1691882055337816720_65464880'
/srv/www/hawk/app/views/nodes/show.html.haml:19:in `each'
/srv/www/hawk/app/views/nodes/show.html.haml:19:in `_app_views_nodes_show_html_haml___1691882055337816720_65464880'

**Comment by krig** [comment]
Alright! Now, at least _this_ issue should be fixed. Thanks for your patience.. the utilization code was a lot more broken than I expected.

**Comment by fibidifips** [comment]
sorry to say, still not working - same error as stated above - ActionView::Template::Error: nil can't be coerced into Fixnum for 1 node.

for the other 3 of the 4 nodes nothing appears(apart of the "overlay"). for that i didn't see any message in logs....

**Comment by krig** [comment]
Hrm, ok. I added a null check in the only place I could find that might have that issue, and it seems to work for me here now.

**Comment by fibidifips** [comment]
ok, funny state now:
1 node is working correct now (the one where hawk is running)
1 node shows the infobox, but no utilization details. 
2 nodes still only show overlay

what could be the reason for that? how does hawk collect data from the other nodes? should be crm_simulate -LU only?

**Comment by krig** [comment]
Yeah, it runs `crm_simulate -LU`. It's probably still some corner case that I'm not hitting here. Can you send me the output from running crm_simulate -LU manually?

**Comment by fibidifips** [comment]
# /usr/sbin/crm_simulate -LU

Current cluster status:
Online: [ lnx0083a lnx0083b lnx0129a lnx0129b ]

 Clone Set: gpfsdmon-clone [gpfsdmon]
     Started: [ lnx0083a lnx0083b lnx0129a lnx0129b ]
 fence_lnx0083a	(stonith:fence_cisco_ucs):	Started lnx0083b
 fence_lnx0083b	(stonith:fence_cisco_ucs):	Started lnx0083a
 cl-info	(ocf::pacemaker:ClusterMon):	Started lnx0129b
 fence_lnx0129a	(stonith:fence_cisco_ucs):	Started lnx0129a
 fence_lnx0129b	(stonith:fence_cisco_ucs):	Started lnx0129b
 lnx0071a	(ocf::heartbeat:VirtualDomain):	Started lnx0129b
 lnx0026a	(ocf::heartbeat:VirtualDomain):	Started lnx0083b
 lnx0053a	(ocf::heartbeat:VirtualDomain):	Started lnx0083b
 lnx0058a	(ocf::heartbeat:VirtualDomain):	Started lnx0129b
 lnx0069a	(ocf::heartbeat:VirtualDomain):	Started lnx0083b
 lnx0043a	(ocf::heartbeat:VirtualDomain):	Started lnx0129a
 lnx0092a	(ocf::heartbeat:VirtualDomain):	Started lnx0083b
 lnx0106a	(ocf::heartbeat:VirtualDomain):	Started lnx0129b
 lnx0107a	(ocf::heartbeat:VirtualDomain):	Started lnx0083b
 lnx0134a	(ocf::heartbeat:VirtualDomain):	Started lnx0083b
 lnx0134b	(ocf::heartbeat:VirtualDomain):	Started lnx0129a
 lnx0078a	(ocf::heartbeat:VirtualDomain):	Started lnx0083b
 lnx0073a	(ocf::heartbeat:VirtualDomain):	Started lnx0129b
 lnx0059a	(ocf::heartbeat:VirtualDomain):	Started lnx0083a
 lnx0092b	(ocf::heartbeat:VirtualDomain):	Started lnx0129b
 lnx0053b	(ocf::heartbeat:VirtualDomain):	Started lnx0129a
 k45RG	(ocf::arz:k45):	Started lnx0129b
 lnx0151a	(ocf::heartbeat:VirtualDomain):	Started lnx0083a
 bbx0002a	(ocf::heartbeat:VirtualDomain):	Started lnx0129a
 bbx0003a	(ocf::heartbeat:VirtualDomain):	Started lnx0129b
 openstack_admin	(ocf::heartbeat:VirtualDomain):	Started lnx0129a
 openstack_ctrl	(ocf::heartbeat:VirtualDomain):	(target-role:Stopped) Stopped
 openstack_nw	(ocf::heartbeat:VirtualDomain):	(target-role:Stopped) Stopped
 openstack_strg	(ocf::heartbeat:VirtualDomain):	(target-role:Stopped) Stopped
 lnx0161a	(ocf::heartbeat:VirtualDomain):	Started lnx0083b
 lnx0162a	(ocf::heartbeat:VirtualDomain):	Started lnx0083a
 lnx0162b	(ocf::heartbeat:VirtualDomain):	Started lnx0083a

Utilization information:
Original: lnx0083a capacity: cpu=32 hv_memory=81920
Original: lnx0083b capacity: cpu=32 hv_memory=81920
Original: lnx0129a capacity: cpu=32 hv_memory=81920
Original: lnx0129b capacity: cpu=32 hv_memory=81920
native_assign_node: gpfsdmon:1 utilization on lnx0083a:
native_assign_node: gpfsdmon:3 utilization on lnx0129b:
native_assign_node: gpfsdmon:2 utilization on lnx0129a:
native_assign_node: gpfsdmon:0 utilization on lnx0083b:
native_assign_node: lnx0059a utilization on lnx0083a: cpu=1 hv_memory=1024
native_assign_node: lnx0162a utilization on lnx0083a: cpu=4 hv_memory=8192
native_assign_node: lnx0162b utilization on lnx0083a: cpu=4 hv_memory=8192
native_assign_node: fence_lnx0129b utilization on lnx0129a:
native_assign_node: fence_lnx0129a utilization on lnx0129b:
native_assign_node: fence_lnx0083b utilization on lnx0083a:
native_assign_node: lnx0151a utilization on lnx0083a: cpu=1 hv_memory=4096
native_assign_node: lnx0026a utilization on lnx0083b: cpu=2 hv_memory=4096
native_assign_node: lnx0053b utilization on lnx0129a: cpu=1 hv_memory=2048
native_assign_node: lnx0053a utilization on lnx0083b: cpu=1 hv_memory=2048
native_assign_node: lnx0069a utilization on lnx0083b: cpu=8 hv_memory=10240
native_assign_node: lnx0092b utilization on lnx0129b: cpu=4 hv_memory=10240
native_assign_node: lnx0092a utilization on lnx0083b: cpu=4 hv_memory=10240
native_assign_node: lnx0107a utilization on lnx0083b: cpu=1 hv_memory=4096
native_assign_node: lnx0134b utilization on lnx0129a: cpu=2 hv_memory=8192
native_assign_node: lnx0134a utilization on lnx0083b: cpu=2 hv_memory=8192
native_assign_node: lnx0078a utilization on lnx0083b: cpu=2 hv_memory=2048
native_assign_node: lnx0161a utilization on lnx0083b: cpu=1 hv_memory=2048
native_assign_node: lnx0043a utilization on lnx0129a: cpu=4 hv_memory=20480
native_assign_node: bbx0002a utilization on lnx0129a: cpu=1 hv_memory=6144
native_assign_node: openstack_admin utilization on lnx0129a: cpu=2 hv_memory=4096
native_assign_node: cl-info utilization on lnx0129b:
native_assign_node: lnx0071a utilization on lnx0129b: cpu=6 hv_memory=10240
native_assign_node: k45RG utilization on lnx0129b:
native_assign_node: bbx0003a utilization on lnx0129b: cpu=2 hv_memory=8192
native_assign_node: lnx0058a utilization on lnx0129b: cpu=2 hv_memory=16384
native_assign_node: lnx0106a utilization on lnx0129b: cpu=1 hv_memory=4096
native_assign_node: lnx0073a utilization on lnx0129b: cpu=1 hv_memory=4096
native_assign_node: fence_lnx0083a utilization on lnx0083b:
Remaining: lnx0083a capacity: cpu=22 hv_memory=60416
Remaining: lnx0083b capacity: cpu=11 hv_memory=38912
Remaining: lnx0129a capacity: cpu=22 hv_memory=40960
Remaining: lnx0129b capacity: cpu=16 hv_memory=28672

Transition Summary:

**Comment by krig** [comment]
And what does going to `/cib/live/nodes.json` return?

Maybe you can make a gist instead of pasting directly in the issue: https://gist.github.com/

Thanks!

**Comment by fibidifips** [comment]
https://gist.github.com/fibidifips/d2a02d46793afa9a380e

**Comment by krig** [comment]
Well, that all looks completely fine. Hmm.

**Comment by fibidifips** [comment]
difference is: percentage value where it is ok, no percentage value where it didn't work

**Comment by fibidifips** [comment]
as far as i understand the remaining value is wrong, on some of the nodes. 
please look at the last 4 lines of crm_simulate output: https://gist.github.com/fibidifips/e8a48ffdc9192601afd8

looks like remaining is equal to total. so 3 of the nodes have percentage 0. should be greater than 0.

**Comment by krig** [comment]
Found it, fix pushed. Thanks again :)

**Comment by fibidifips** [comment]
yes, works fine now! thank you!
